#!groovy
node {

    def err = null
    currentBuild.result = "SUCCESS"

    try {
       stage 'Checkout'
            checkout scm

       stage 'Deploy'
            echo 'Push to int-server'
	    sh 'int-sp-instantiation/deployment.sh'

       stage 'Testing'
            echo 'Testing Phase'
            sh 'int-sp-instantiation/tests.sh'

       stage 'Notifications'
            echo 'Sending mails'

            mail body: 'project build successful',
                        from: 'sonata-nfv@gmail.com',
                        replyTo: 'sonata-nfv@gmail.com',
                        subject: 'project build successful',
                        to: 'felipe.vicens@atos.net, manuel.peuster@upb.de'
        }


    catch (caughtError) {
        err = caughtError
        currentBuild.result = "FAILURE"
            mail body: "project build error: ${err}" ,
            from: 'sonata-nfv@gmail.com',
            replyTo: 'sonata-nfv@gmail.com',
            subject: 'project build error',
            to: 'felipe.vicens@atos.net, manuel.peuster@upb.de'
        }

    finally {
        /* Must re-throw exception to propagate error */
        if (err) {
            throw err
        }

    }

}
