#!groovy
node {

    def err = null
    currentBuild.result = "SUCCESS"

    try {
       stage 'Checkout'
            checkout scm
			sh 'chmod +x int-service-instantiation/*.sh'
			sh 'chmod +x int-service-instantiation/scripts/*.sh'

       stage 'Deploy'
            echo 'Push to int-server'			
			sh 'int-service-instantiation/deployment.sh'

       stage 'Testing'
            echo 'Testing Phase'
            sh 'int-service-instantiation/tests.sh'
			
	   stage 'Showing report'
			echo 'Showing report'
			publishHTML(target: [allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'reports', reportFiles: '*.html', reportName: 'HTML Report'])

       stage 'Notifications'
            echo 'Sending mails'
       
        }


    catch (caughtError) {
        err = caughtError
        currentBuild.result = "FAILURE"            
        }

    finally {
        /* Must re-throw exception to propagate error */
        if (err) {
            throw err
        }

    }

}