#!groovy
node {

    def err = null
    currentBuild.result = "SUCCESS"

    try {
       stage 'Checkout'
            checkout scm
			sh 'chmod +x int-bss-gkeeper/scripts/*.sh'

       stage 'Deploy'
            echo 'Push to int-server'			
			sh 'int-bss-gkeeper/deployment.sh'

       stage 'Testing'
            echo 'Testing Phase'
            sh 'int-bss-gkeeper/tests.sh'
	}
    catch (caughtError) {
        err = caughtError
        currentBuild.result = "FAILURE"
            mail body: "project build error: ${err}" ,
            from: 'srodriguez@optaresolutions.com',
            subject: 'project build error',
            to: 'srodriguez@optaresolutions.com'
        }

    finally {
        /* Must re-throw exception to propagate error */
        if (err) {
            throw err
        }

    }

}
